application:
  name: blazer-docker
  project: blazer-docker
  publicly_accessible: true
  organization: QoveryCommunity
databases:
- type: postgresql
  version: "12"
  name: my-postgresql-7274989
routers:
- name: main
  routes:
  - application_name: blazer-docker
    paths:
    - /
